### ISSUE TITLE
Errno 32 Broken Pipe

### ISSUE THREAD

**Issue by jjp55** [loosolab/UROPA#7]
Hello, 

I recently installed UROPA using:

conda install -c bioconda uropa

And the package was able to install and I can see the options when I use: uropa -h.

I tried to run the code:

uropa -b Arabidopsis_w50_g2_PE.bed -g /Users/jjp/Desktop/TAIR10_GFF3_genes.gff --feature protein_coding -o Arabidopsis-UROPA

Afterwards, I received the following message:

2021-06-14 13:46:56 (34865) [INFO]	Started UROPA 4.0.1
2021-06-14 13:46:56 (34865) [INFO]	Working directory: /Users/jjp/Desktop/new_HOMER
2021-06-14 13:46:56 (34865) [INFO]	Command-line call: /Users/jjp/opt/anaconda3/envs/epic/bin/uropa -b NPR1-SA-SICER_w50_g2_PE.bed -g /Users/jjp/Desktop/TAIR10_GFF3_genes.gff --feature protein_coding -o NPR1-SA-SICER-UROPA
2021-06-14 13:46:56 (34865) [INFO]	Reading configuration from commandline/input config
2021-06-14 13:46:56 (34865) [INFO]	Preparing .gtf-file for fast access
2021-06-14 13:46:58 (34865) [INFO]	Config key show_attributes was set to 'all'.

Followed by was appears to be all the genes in the Arabidopsis genome. (example 'Parent=ATMG01410.1')

After the gene list prints I received the following message:
Traceback (most recent call last):
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/site-packages/uropa/utils.py", line 88, in main_logger_process
    record = self.q.get()
  File "<string>", line 2, in get
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

Do you have any way to solve this or know what may have caused the error?

**Comment by msbentsen** [comment]
Hi jjp55,

UROPA unfortunately only reads .gtf files, and not .gff, so that might be part of the issue here. This is also why it prints all the genes, as it thinks these are all different features from a .gtf-file. I don't know if this is the reason for the BrokenPipe (which seems to be the same error as #6).

For the error, can you give me some more information on the system you are on? And at exactly which point the pipeline fails? E.g. by the last written print before the error. Thank you!

**Comment by jjp55** [comment]
That was a complete oversight on my part. Using a .gtf-gile completely fixed the problem. 

I am running on a Mac with Big Sur.

**Comment by jjp55** [comment]
But when I ran the code:

$ uropa -b SICER_w50_g2_PE.bed -g /Users/jjp/Desktop/Arabidopsis_thaliana.TAIR10.51.gtf --attribute-value protein_coding -o NPR1-SA-SICER-UROPA

I get the following message followed by the same Broken Pipe Error. 

2021-06-15 10:44:19 (48336) [INFO]	Started UROPA 4.0.1
2021-06-15 10:44:19 (48336) [INFO]	Working directory: /Users/jjp/Desktop/new_HOMER
Process Process-2:
Traceback (most recent call last):
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/site-packages/uropa/utils.py", line 88, in main_logger_process
    record = self.q.get()
  File "<string>", line 2, in get
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/Users/jjp/opt/anaconda3/envs/epic/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by msbentsen** [comment]
Great! I saw you wrote another comment - was that solved in the meantime?
